#!/usr/bin/env bash

set -e

if [ -f /root/.provisioned-couchbase ]; then
  echo "Couchbase already provisioned"
  exit 0
fi

echo "INSTALLING: Couchbase..."

COUCHPATH=/vagrant/couchbase.deb

if [ ! -e "$COUCHPATH" ]; then
  wget -qO $COUCHPATH http://packages.couchbase.com/releases/2.2.0/couchbase-server-enterprise_2.2.0_x86_64.deb
fi

apt-get -y install libssl0.9.8
dpkg -i $COUCHPATH
echo 'PATH=$PATH:/opt/couchbase/bin' >> ~/.bash_profile

touch /root/.provisioned-couchbase

exit 0
